editor: EditorView Class Reference
EditorView Class Reference
Class EditorView (MVC).
#include <EditorView.h>
Public Member Functions
EditorView (std::shared_ptr< EditorModel > model, std::shared_ptr< EditorController > controller)
void new_document_click ()
void export_to_file_click ()
void import_from_file_click ()
void create_line_click (const Point &a, const Point &b)
void create_rectangle_click (const Point &a, const Point &b)
void create_triangle_click (const Point &a, const Point &b, const Point &c)
void create_circle_click (const Point &a, float r)
void delete_figure_click (std::size_t id)
Private Member Functions
void update_view ()
Static Private Member Functions
static void draw_figure (const std::shared_ptr< Figure > &figure)
static void clear_view ()
Private Attributes
std::shared_ptr< EditorModel > _model
std::shared_ptr< EditorController > _controller
Detailed Description
Class EditorView (MVC).
Definition at line 14 of file EditorView.h.
Constructor & Destructor Documentation
EditorView()
EditorView::EditorView (std::shared_ptr< EditorModel > model, std::shared_ptr< EditorController > controller) inline
Definition at line 16 of file EditorView.h.
                                                                                             :
    _model(std::move(model)), _controller(std::move(controller)) {};
Member Function Documentation
clear_view()
void EditorView::clear_view () static private
Definition at line 24 of file EditorView.cpp.
{
    //
    std::cout << "View is cleared." << std::endl;
    //
}
Referenced by new_document_click(), and update_view().
create_circle_click()
void EditorView::create_circle_click (const Point & a, float r)
Definition at line 59 of file EditorView.cpp.
{
    _controller->add_figure(Circle(a, r));
    update_view();
}
create_line_click()
void EditorView::create_line_click (const Point & a, const Point & b)
Definition at line 44 of file EditorView.cpp.
{
    _controller->add_figure(Line(a, b));
    update_view();
}
create_rectangle_click()
void EditorView::create_rectangle_click (const Point & a, const Point & b)
Definition at line 49 of file EditorView.cpp.
{
    _controller->add_figure(Rectangle(a, b));
    update_view();
}
create_triangle_click()
void EditorView::create_triangle_click (const Point & a, const Point & b, const Point & c)
Definition at line 54 of file EditorView.cpp.
{
    _controller->add_figure(Triangle(a, b, c));
    update_view();
}
delete_figure_click()
void EditorView::delete_figure_click (std::size_t id)
Definition at line 64 of file EditorView.cpp.
{
    _controller->delete_figure(id);
    update_view();
}
draw_figure()
void EditorView::draw_figure (const std::shared_ptr< Figure > & figure) static private
Definition at line 17 of file EditorView.cpp.
{
    //
    std::cout << "A figure is drawn: ";
    figure->draw();
    //
}
Referenced by update_view().
export_to_file_click()
void EditorView::export_to_file_click ()
Definition at line 35 of file EditorView.cpp.
{
    _controller->export_to_file();
}
import_from_file_click()
void EditorView::import_from_file_click ()
Definition at line 39 of file EditorView.cpp.
{
    _controller->import_from_file();
    update_view();
}
new_document_click()
void EditorView::new_document_click ()
Definition at line 30 of file EditorView.cpp.
{
    _controller->new_document();
    clear_view();
}
update_view()
void EditorView::update_view () private
Definition at line 3 of file EditorView.cpp.
{
    //
    Action action = _controller->get_last_action();
    if (action == Action::RemoveFigure || action == Action::NewDocument || action == Action::OpenDocument) {
        clear_view();
        for (const auto& [current_id, figure] : _model->get_figures()) {
            draw_figure(figure);
        }
    } else if (action == Action::AddFigure) {
        draw_figure(_model->get_figures().find(_controller->get_last_id())->second);
    }
    //
}
Referenced by create_circle_click(), create_line_click(), create_rectangle_click(), create_triangle_click(), delete_figure_click(), and import_from_file_click().
Member Data Documentation
_controller
std::shared_ptr<EditorController> EditorView::_controller private
Definition at line 35 of file EditorView.h.
Referenced by create_circle_click(), create_line_click(), create_rectangle_click(), create_triangle_click(), delete_figure_click(), export_to_file_click(), import_from_file_click(), new_document_click(), and update_view().
_model
std::shared_ptr<EditorModel> EditorView::_model private
Definition at line 34 of file EditorView.h.
Referenced by update_view().
The documentation for this class was generated from the following files:
EditorView.h
EditorView.cpp